version: '3.3'
services:
  odoo:
    image: $IMAGE
    environment:
      HOST: $HOST
      PASSWORD: $PASSWORD
    ports:
      - 8077:8069
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.$name.rule=Host(`$domaine`)"   
        - "traefik.http.routers.$name.entrypoints=web"
        - "traefik.http.routers.$name.service=$name"
        - "traefik.http.services.$name.loadbalancer.server.port=8069"         
        - "traefik.http.routers.$name+_long.rule=Host(`$domaine`) && PathPrefix(`/longpolling/`)"
        - "traefik.http.routers.$name+_long.entrypoints=web"
        - "traefik.http.routers.$name+_long.service=$name+_long"
        - "traefik.http.services.$name+_long.loadbalancer.server.port=8072" 
    configs:
      - source: odoo.conf
        target: /opt/odoo/etc/odoo.conf
    volumes:
      - odoo-data:/opt/odoo/data
    networks:
      - web
      - db

configs:
  odoo.conf:
    external: true

volumes:
  odoo-data:

networks:
  web:
    external: true
  db:
    external: true
